In [ ]:
"""Block 3: Simulation & Aggregation
Focus: Random data, simulation, basic stats

 1  Generate 1000 values from normal distribution
 2  Count how many > 1.0
 3  Create a 5x5 matrix of random integers 09
 4  Calculate row-wise and column-wise mean
 5  Simulate rolling 2 dice 10000 times
 6  Get frequency of each sum from dice rolls
 7  Find standard deviation of an array
 8  Replace all values in array > 2 stds from mean with mean
 9  Generate 3 matrices and stack them
 10  Flatten any n-dimensional array"""

In [1]:
import numpy as np
arr1_data = np.random.normal(loc = 0, scale = 1, size = 1000)
print(arr1_data)

[ 6.64144923e-02 -5.66648901e-01  7.89670543e-01  5.41763746e-02
 -1.55223013e+00 -4.10335578e-01 -4.08282989e-01 -2.19828109e+00
 -3.27393585e-02 -1.40618847e+00  1.68378759e+00  3.06339789e-01
  9.89060689e-01  4.46114699e-01 -8.34391183e-01  3.59599603e-01
  1.13959110e-01  1.00654417e+00 -3.87221351e-01  8.04865352e-02
 -1.66274803e-01  5.14090426e-01  1.03849380e-01  1.39311625e+00
  1.69532171e+00 -8.83544314e-02 -7.64547967e-01 -1.63364675e-01
 -5.21982592e-01  1.83850852e+00 -1.03960604e+00 -1.32215861e-01
  8.66233192e-01 -1.77414786e+00 -2.08805366e+00 -1.96605045e+00
  3.04195823e-02  9.53405833e-01 -1.13518409e-02 -8.67471859e-01
  3.36277824e-01 -1.14973585e+00 -1.09045669e+00  3.59434125e-01
 -1.65883769e+00  1.82674524e-01 -1.12876129e+00  7.59578225e-01
  1.23430833e+00  1.03426908e+00 -4.08636442e-03  1.13140010e+00
  1.19927488e+00  4.65769909e-02 -9.80859348e-01  5.40235973e-01
 -9.78534776e-01 -6.18764679e-01  8.19650611e-01 -1.15961825e+00
  5.50002770e-01  6.41291

In [3]:
mask = arr1_data > 1.0
arr1_check = np.sum(mask)
print(arr1_check)
"""or
arr1_check = arr1[mask]
print(arr1_check.size)"""


159


In [4]:
arr3 = np.random.randint(0,10,(5,5))
print(arr3)
mean_4_0= np.mean(arr3, axis = 0) #column wise, from upside down
mean_4_1 = np.mean(arr3, axis = 1) #row wise, from left to right

[[2 9 0 6 2]
 [1 9 8 6 7]
 [7 5 7 1 5]
 [3 8 9 6 5]
 [0 7 3 7 8]]


In [6]:
dice_1 = np.random.randint(1,7,size = 1000)
dice_2 = np.random.randint(1,7,size = 1000)
total = dice_1 + dice_2
frequency = np.bincount(total)
for i in range (2,13) :
    print(f"Sum {i} is appeared {frequency[i]} times")

Sum 2 is appeared 40 times
Sum 3 is appeared 38 times
Sum 4 is appeared 87 times
Sum 5 is appeared 118 times
Sum 6 is appeared 139 times
Sum 7 is appeared 152 times
Sum 8 is appeared 130 times
Sum 9 is appeared 116 times
Sum 10 is appeared 84 times
Sum 11 is appeared 65 times
Sum 12 is appeared 31 times


In [9]:
arr7 = np.random.randint(2,14, size = 15)
arr7_std = np.std(arr7)
arr7_mean = np.mean(arr7)
if arr7_std < (arr7_mean / 10) :
    print("the numbers are very close to each other")
if arr7_std > (arr7_mean * 0.3) :
    print("the numbers are spread from each other")    
        

the numbers are spread from each other


In [ ]:
arr8 = np.random.randint(0,100, size = 20)
arr8_mean = np.mean(arr8)
arr8_std = np.std(arr8)
#if num is outlier abs(num - mean) > 2 * std, [usual formula]
#if we want to be stricker abs(num -mean) > 3 * std, [strong outlier]
mask = abs(arr8 -  mean) > 2 * arr8_std
arr8[mask] = arr8_mean


In [3]:
#ex 9
import numpy as np
mat1 = np.random.randint(0,13,size = (1,3))
mat2 = np.random.randint(0,13,size = (1,3))
mat3 = np.random.randint(0,13,size = (1,3))
h_stack = np.hstack((mat1,mat2,mat3))
print(h_stack)
v_stack = np.vstack((mat1,mat2,mat3))
print(v_stack)

[[12  3  8  5  3  5  0  2  2]]
[[12  3  8]
 [ 5  3  5]
 [ 0  2  2]]


In [4]:
arr10 = np.random.randint(0,15,size = (3,4))
flat = arr10.flatten()
print(flat)
#or
#flat = arr10.reshape(-1) works the same

[10  0  4  1  5  7  7  2  4  5  0 12]
