In [ ]:
"""Block 2: Boolean Masking & Advanced Indexing
Focus: Select/filter elements using logic

 1  Find all values > 50 in a random array
 2  Replace all negatives in an array with 0
 3  Extract only even numbers from a 2D matrix
 4  Count how many numbers are between 10 and 30
 5  Create a mask for numbers divisible by 3
 6  Apply mask and replace them with 999
 7  Get the indices of all elements > 25
 8  Use .where() to select values with a condition
 9  Set all values in row 1 that are < 50 to 0
 10  Extract diagonal using np.diag()"""

In [7]:
import numpy as np
arr1 = np.random.randint(1,101,(5,5))
mask = arr1 > 50
greater_than_50 = arr1[mask]
print(arr1)
print(greater_than_50)


[[64 47 75 79 43]
 [29 24 17 74 25]
 [31 26  7 55 16]
 [38  6 87 95 73]
 [25 40 94 53 80]]
[64 75 79 74 55 87 95 73 94 53 80]


In [15]:
arr2 = np.random.randint(-100,100,(3,4))
print(arr2)
mask = arr2 < 0
arr2[mask] = 0
print(arr2)

[[-30 -92  21  11]
 [ 72  20  60 -11]
 [-70  23 -52 -26]]
[[ 0  0 21 11]
 [72 20 60  0]
 [ 0 23  0  0]]


In [14]:
arr3 = np.random.randint(0,101,(3,4))
print(arr3)
mask = arr3 % 2 == 0
arr3_even = arr3[mask]
print(arr3_even)

[[30 99 15 91]
 [55 63  5 19]
 [86  0 17 36]]
[30 86  0 36]


In [17]:
arr4 = np.random.randint(0,101,(4,5))
print(arr4)
mask = (arr4 < 30) & (arr4 > 10)
arr4_between_10_30 = arr4[mask]
print(arr4_between_10_30)

[[10 29 96 69 49]
 [54 99 23 57 86]
 [41 76 60 18 31]
 [ 2 30 35 81 17]]
[29 23 18 17]


In [19]:
arr5 = np.random.randint(-50,50,(4,5))
print(arr5)
mask = arr5 % 3 == 0
arr5[mask] = 999
print(arr5)

[[ 16 -50  14 -17  27]
 [ 37  -6  -2 -41  29]
 [-40   6 -42  45  -6]
 [-12 -31   5  26  11]]
[[ 16 -50  14 -17 999]
 [ 37 999  -2 -41  29]
 [-40 999 999 999 999]
 [999 -31   5  26  11]]


In [24]:
arr7 = np.random.randint(0,51,(4,5))
print(arr7)
indices = np.where(arr7 > 25)
positions = list(zip(*indices))
positions =[(int(x),int(y)) for x,y in positions]
print(positions)

[[ 7 32 15 30  1]
 [28 13 32 22 19]
 [48 35  6 19 13]
 [26 38 31 14 21]]
[(0, 1), (0, 3), (1, 0), (1, 2), (2, 0), (2, 1), (3, 0), (3, 1), (3, 2)]


In [26]:
arr8 = np.random.randint(-100,100,(4,5))
print(arr8)
result = np.where(arr8 < 0, 0,arr8)
print(result)

[[ 71  43 -18 -81 -59]
 [-19  18 -49  26 -90]
 [-47  31 -15  -8 -89]
 [ 84 -97  12  74  67]]
[[71 43  0  0  0]
 [ 0 18  0 26  0]
 [ 0 31  0  0  0]
 [84  0 12 74 67]]


In [27]:
arr9 = np.random.randint(0,100,(4,5))
print(arr9)
mask = arr9[1] < 50
arr9[1][mask] = 0
print(arr9)

[[20 58 24 85 91]
 [35 33 99 78 96]
 [31 75 73 30 46]
 [33 95 70 49 91]]
[[20 58 24 85 91]
 [ 0  0 99 78 96]
 [31 75 73 30 46]
 [33 95 70 49 91]]


In [28]:
arr10 = np.random.randint(1,101,(4,5))
diagonal = np.diag(arr10)
print(arr10)
print(diagonal)

[[42 71 72 27 36]
 [94 71 93 88 56]
 [36 32 56 46 86]
 [77 17  6 11 20]]
[42 71 56 11]
